name: cora
favicon: null
layout_spectrum: 1
typography_spectrum: 0.47748
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cbcbcb'
    - '#eaeaea'
    - '#050505'
    - '#797979'
    - '#4e4e4e'
  brandStrength: 1
  lightness: 0.5625
  saturation: null
  rhythmicContrast: 0.5
purpose: []
