name: cora
favicon: null
layout_spectrum: 1
typography_spectrum: 0.46548
title: Cora Hirashiki
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#73eae0'
    - '#000000'
    - '#ffffff'
    - '#55aaaa'
    - '#00ff00'
  brandStrength: 0.5
  lightness: 0.9550587141420692
  saturation: 1
  rhythmicContrast: 0.9963978822343051
purpose: []
